# Generated by Django 6.0.6 on 2026-06-18 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='companies',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=50)),
                ('About', models.TextField()),
                ('Type', models.CharField(choices=[('IT', 'IT'), ('NON TECH', 'NON TECH'), ('MOBILE APP', 'MOBILE APP'), ('AUTOMATION', 'AUTOMATION')], max_length=20)),
                ('Active', models.BooleanField(default=True)),
            ],
        ),
    ]
